### ISSUE TITLE
Multiple dependencies for locked accomplishments need spacing

### ISSUE THREAD

**Issue by stuartlangridge** [UbuntuAccomplishments/daemon#2]
![image](https://user-images.githubusercontent.com/4356350/143260902-8685ead3-528f-443b-9027-97b678917ed3.png)

This should maybe be something like "This trophy is currently locked because you have not accomplished __Thing 1__, **Thing 2**, or **Thing 3**".

**Comment by lucyllewy** [comment]
This one is already fixed, and will be released shortly :-)

**Comment by lucyllewy** [comment]
released to stable...
